project:
  type: website
  render:
    - "*.md"
    - README.md
    - nantes/README.md
    - irdp/README.md
    - ias/README.md
    - univ-toulouse/README.md
    
website:
  title: "Open Education Mission"
